### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by nblackburn** [wildbit/laravel-postmark-provider#1]
Just a heads up to let you know that this library doesn't seem to work for Laravel 5.1.

If i find some spare time, i will take a look and see if i can find the cause of the problem and potentially if there is a solution for it.

**Comment by atheken** [comment]
Thanks, we'll have a look and get it fixed.

//Andrew

**Comment by nblackburn** [comment]
Thanks, i very much appreciate your quick response and absolutely love the service.

**Comment by nblackburn** [comment]
Under further investigation it seems like there could well be a fault on my end during the upgrade to 5.1 causing complications, i will let you know should this be the problem.

**Comment by nblackburn** [comment]
Fixed. It was a fault on my end, everything seems to be working perfectly now.

**Comment by atheken** [comment]
Well, that was easy. @nblackburn If you have a minute, can you tell me what the fix was? Maybe we can update the readme/docs in case other folks hit the same issue.

**Comment by nblackburn** [comment]
Entirely on me this one, i somehow missed out the **EventServiceProvider** during the upgrade which acts as the registrar for custom events (_some of which send emails_) so they wen't even registered.

---

The only thing i could think of to add to the readme on a sidenote is cURL is kind of fussy on Windows so it might we worth mentioning about **cacert.pem** incase people are having problems with that (_seems a very common problem but is simple to fix_).
- Download **cacert.pem** from here: http://curl.haxx.se/docs/caextract.html
- Find **curl.cainfo** in **php.ini**, **uncomment** it and **set** the value to the **absolute** location of **cacert.pem**.
